# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "qtv-stark"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Hash based STARK backend for Quantova."

[dependencies]
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "21e28f1ffd1ca46a7144136c483618b18cd29bae" }

[[bench]]
name = "backend"
harness = false

[[bench]]
name = "batch"
harness = false

[[bench]]
name = "certificate"
harness = false

[[bench]]
name = "general"
harness = false

[[bench]]
name = "lattice"
harness = false

[[bench]]
name = "hashing"
harness = false

[[bench]]
name = "qudros"
harness = false

[[bench]]
name = "ntt"
harness = false

[[bench]]
name = "sampling"
harness = false

[[bench]]
name = "signing"
harness = false

[[bench]]
name = "sponge"
harness = false

[[bench]]
name = "verify"
harness = false
