[package]
name = "qtv-stark"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Hash based STARK backend for Quantova."

[dependencies]
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", tag = "v0.1.0" }

[[bench]]
name = "backend"
harness = false

[[bench]]
name = "general"
harness = false

[[bench]]
name = "lattice"
harness = false

[[bench]]
name = "keccak"
harness = false

[[bench]]
name = "ntt"
harness = false

[[bench]]
name = "sponge"
harness = false

[[bench]]
name = "verify"
harness = false
