# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    uses: Quantova/Quantova-Ci/.github/workflows/rust-ci.yml@f2a7a9c5bee34b20876b110ba903d0008b9e90d1
